<?php


return array(
    0 =>
        array(
            'users_id' => '95',
            'nomor_identitas' => '3512700087914881',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '-',
            'no_telepon' => '087899685680',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    1 =>
        array(
            'users_id' => '96',
            'nomor_identitas' => '351270008714882',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '0',
            'no_telepon' => '088235437576',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    2 =>
        array(
            'users_id' => '97',
            'nomor_identitas' => '3512700087914883',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '9',
            'no_telepon' => '081333393447',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    3 =>
        array(
            'users_id' => '98',
            'nomor_identitas' => '3512700087914884',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '8',
            'no_telepon' => '085942338369',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    4 =>
        array(
            'users_id' => '99',
            'nomor_identitas' => '3512700087914885',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '7',
            'no_telepon' => '085707116893',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    5 =>
        array(
            'users_id' => '100',
            'nomor_identitas' => '3512700087914886',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '6',
            'no_telepon' => '089680555501',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    6 =>
        array(
            'users_id' => '101',
            'nomor_identitas' => '351700087914885',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '5',
            'no_telepon' => '085733404002',
            'alamat' => '-',
            'limit_pinjaman' => '10000000',
        ),
    7 =>
        array(
            'users_id' => '102',
            'nomor_identitas' => '3512700087914888',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '4',
            'no_telepon' => '081234921692',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    8 =>
        array(
            'users_id' => '103',
            'nomor_identitas' => '3512700087914889',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '3',
            'no_telepon' => '082301731212',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    9 =>
        array(
            'users_id' => '104',
            'nomor_identitas' => '3512700087914810',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '2',
            'no_telepon' => '083179484188',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    10 =>
        array(
            'users_id' => '105',
            'nomor_identitas' => '3512700087914811',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '1',
            'no_telepon' => '085648072231',
            'alamat' => '-',
            'limit_pinjaman' => '60000000',
        ),
    11 =>
        array(
            'users_id' => '106',
            'nomor_identitas' => '3512700087914812',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '11',
            'no_telepon' => '081351872523',
            'alamat' => '-',
            'limit_pinjaman' => '5000000',
        ),
    12 =>
        array(
            'users_id' => '107',
            'nomor_identitas' => '3512700087914813',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '12',
            'no_telepon' => '085106361017',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    13 =>
        array(
            'users_id' => '108',
            'nomor_identitas' => '3512700087914814',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '13',
            'no_telepon' => '089523820153',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    14 =>
        array(
            'users_id' => '109',
            'nomor_identitas' => '3512700087914815',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '14',
            'no_telepon' => '082330793578',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    15 =>
        array(
            'users_id' => '110',
            'nomor_identitas' => '3512700087914816',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '15',
            'no_telepon' => '081233634340',
            'alamat' => '-',
            'limit_pinjaman' => '5000000',
        ),
    16 =>
        array(
            'users_id' => '111',
            'nomor_identitas' => '3512700087914817',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '16',
            'no_telepon' => '082141482769',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    17 =>
        array(
            'users_id' => '112',
            'nomor_identitas' => '3512700087914818',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '17',
            'no_telepon' => '082264651089',
            'alamat' => '-',
            'limit_pinjaman' => '5000000',
        ),
    18 =>
        array(
            'users_id' => '113',
            'nomor_identitas' => '3512700087914819',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '18',
            'no_telepon' => '085335394153',
            'alamat' => '-',
            'limit_pinjaman' => '5000000',
        ),
    19 =>
        array(
            'users_id' => '114',
            'nomor_identitas' => '3512700087914820',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '19',
            'no_telepon' => '085736494914',
            'alamat' => '-',
            'limit_pinjaman' => '10000000',
        ),
    20 =>
        array(
            'users_id' => '115',
            'nomor_identitas' => '3512700087914821',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '20',
            'no_telepon' => '081233180087',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    21 =>
        array(
            'users_id' => '116',
            'nomor_identitas' => '3512700087914822',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '21',
            'no_telepon' => '085161535430',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    22 =>
        array(
            'users_id' => '117',
            'nomor_identitas' => '3512700087914823',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '22',
            'no_telepon' => '081333287418',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    23 =>
        array(
            'users_id' => '118',
            'nomor_identitas' => '3512700087914824',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '23',
            'no_telepon' => '081259306820',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    24 =>
        array(
            'users_id' => '119',
            'nomor_identitas' => '3512700087914825',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '24',
            'no_telepon' => '0895366998510',
            'alamat' => '-',
            'limit_pinjaman' => '5000000',
        ),
    25 =>
        array(
            'users_id' => '120',
            'nomor_identitas' => '3512700087914826',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '25',
            'no_telepon' => '081234316529',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    26 =>
        array(
            'users_id' => '121',
            'nomor_identitas' => '3512700087914827',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '26',
            'no_telepon' => '082245907718',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    27 =>
        array(
            'users_id' => '122',
            'nomor_identitas' => '3512700087914828',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '27',
            'no_telepon' => '081334528424',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    28 =>
        array(
            'users_id' => '123',
            'nomor_identitas' => '3512700087914829',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '28',
            'no_telepon' => '085236397248',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    29 =>
        array(
            'users_id' => '124',
            'nomor_identitas' => '3512700087914830',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '29',
            'no_telepon' => '081334851289',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    30 =>
        array(
            'users_id' => '125',
            'nomor_identitas' => '3512700087914831',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '30',
            'no_telepon' => '085942338369',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    31 =>
        array(
            'users_id' => '126',
            'nomor_identitas' => '3512700087914832',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '31',
            'no_telepon' => '085735863873',
            'alamat' => '-',
            'limit_pinjaman' => '0',
        ),
    32 =>
        array(
            'users_id' => '128',
            'nomor_identitas' => '3512700087914833',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '33',
            'no_telepon' => '082139647470',
            'alamat' => 'Pujon',
            'limit_pinjaman' => '5000000',
        ),
    33 =>
        array(
            'users_id' => '129',
            'nomor_identitas' => '3512700087914835',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '501',
            'no_telepon' => '0881027969677',
            'alamat' => '-',
            'limit_pinjaman' => '15000000',
        ),
    34 =>
        array(
            'users_id' => '130',
            'nomor_identitas' => '352700087914899',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '99',
            'no_telepon' => '082145983325',
            'alamat' => 'Pujon',
            'limit_pinjaman' => '5000000',
        ),
    35 =>
        array(
            'users_id' => '131',
            'nomor_identitas' => '3512700087914188',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '88',
            'no_telepon' => '081234785234',
            'alamat' => 'Pujon',
            'limit_pinjaman' => '5000000',
        ),
    36 =>
        array(
            'users_id' => '132',
            'nomor_identitas' => '3512700087914898',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '2398',
            'no_telepon' => '082333331300',
            'alamat' => 'batu',
            'limit_pinjaman' => '100000000',
        ),
    37 =>
        array(
            'users_id' => '133',
            'nomor_identitas' => '3512700087914807',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '79',
            'no_telepon' => '081280177558',
            'alamat' => 'Batu',
            'limit_pinjaman' => '5000000',
        ),
    38 =>
        array(
            'users_id' => '134',
            'nomor_identitas' => '3512700087914841',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => '1l',
            'no_telepon' => '08123361462',
            'alamat' => 'batu',
            'limit_pinjaman' => '5000000',
        ),
    39 =>
        array(
            'users_id' => '135',
            'nomor_identitas' => '3512700087914863',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => 'daffa',
            'no_telepon' => '082139156263',
            'alamat' => 'batu',
            'limit_pinjaman' => '5000000',
        ),
    40 =>
        array(
            'users_id' => '136',
            'nomor_identitas' => '3512700087914895',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => 'mrx',
            'no_telepon' => '082139156263',
            'alamat' => 'batu',
            'limit_pinjaman' => '5000000',
        ),
    41 =>
        array(
            'users_id' => '137',
            'nomor_identitas' => '3512700087914878',
            'identitas_type' => 'KTP',
            'foto_identitas' => '',
            'keterangan' => '',
            'tahun_lahir' => '',
            'email' => 'ded',
            'no_telepon' => '082231046360',
            'alamat' => 'Batu',
            'limit_pinjaman' => '5000000',
        ),
);
